name = "aissist-app"
main = "app/api/workers/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Bindings - Add the AI binding
[ai]
binding = "AI"

# Dev options
[dev]
port = 8081

[vars]
CLOUDFLARE_ACCOUNT_ID = "9b37eea8034fbf61191d273e000f450e"

[observability]
enabled = true