name = "aissist-app"
main = "services/workers.ts"
compatibility_date = "2024-07-31"


# Bindings - Add the AI binding
[ai]
binding = "AI"

# Dev options
[dev]
port = 8081

[vars]
CLOUDFLARE_ACCOUNT_ID = "9b37eea8034fbf61191d273e000f450e"

[observability]
enabled = true