import { CustomButton } from '@/components/Button';
import { ThemedText } from '@/components/ThemedText';
import { ThemedView } from '@/components/ThemedView';
import { Image, StyleSheet, useColorScheme, View } from 'react-native';
import * as FileSystem from 'expo-file-system';
import { CustomTextInput } from '@/components/TextInput';
import { useGenerateImage } from '@/hooks/useGenerateImage';
import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { colors } from '@/constants/theme';
import { ScrollView } from 'react-native-gesture-handler';

export default function ImagesScreen() {
  const { generateImageUsingAi, generatedImage, loading, setInput, input } = useGenerateImage();
  const [inputHeight, setInputHeight] = useState<number>(0);
  const colorScheme = useColorScheme();
  console.log(loading);

  return (
    <ThemedView style={styles.container}>
      <ScrollView>
        {generatedImage?.map((item) => (
          <ThemedView key={item.requestId} style={[styles.imageCard, { borderColor: colorScheme === 'dark' ? colors.lightBlack : colors.whitesmoke }]}>
            <Image source={{ uri: item?.images[0]?.url }} width={item?.images[0]?.width} height={item?.images[0]?.height} style={{ flex: 1, width: null, height: null, resizeMode: 'cover' }} />
            <ThemedText type="subtitle" style={{ padding: 10, color: 'gray' }}>
              Generated by Fal.ai
            </ThemedText>
          </ThemedView>
        ))}
        {loading && <ThemedText style={{ fontSize: 30 }}>Loading!!</ThemedText>}
      </ScrollView>

      <View style={styles.inputContainer}>
        <CustomTextInput multiline={true} style={styles.textInput} onChangeText={setInput} onContentSizeChange={(event) => setInputHeight(event.nativeEvent.contentSize.height)} value={input} placeholder="Make something unique!" />

        <CustomButton
          style={[styles.button, { height: Math.max(35, inputHeight) }]}
          onPress={() => generateImageUsingAi('Photo of a rhino dressed suit and tie sitting at a table in a bar with a bar stools, award winning photography, Elke vogelsang')}
        >
          <Ionicons name="send" color={colorScheme === 'light' ? 'dark' : 'white'} size={18} />
        </CustomButton>
      </View>
    </ThemedView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    display: 'flex',
    justifyContent: 'space-between',
    gap: 10,
    padding: 18,
  },
  imageCard: {
    height: 400,
    width: '100%',
    borderRadius: 12,
    borderWidth: 2,
    overflow: 'hidden',
  },
  textInput: {
    flex: 1,
    borderWidth: 2,
    borderRadius: 12,
    padding: 12,
  },
  inputContainer: {
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
  button: {
    position: 'absolute',
    backgroundColor: 'transparent',
    right: 12,
    top: 15,
  },
});
